export const GET_RECIPE_REQUEST='GET_RECIPE_REQUEST';
export const GET_RECIPE_SUCCESS='GET_RECIPE_SUCCESS';
export const GET_RECIPE_FAILURE='GET_RECIPE_FAILURE';

export const LOGIN_REQUEST='LOGIN_REQUEST';
export const LOGIN_SUCCESS='LOGIN_SUCCESS';
export const LOGIN_FAILURE='LOGIN_FAILURE';

export const SIGNIN_SUCCESS='SIGNIN_SUCCESS';